In [1]:
from Embedder import Embedder
from dotenv import load_dotenv

c:\Users\sgt17\OneDrive\Desktop\RAG_system\GPT_embedding\.conda\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
load_dotenv()

True

## OpenAI Embedding (text-embedding-3-small)

In [3]:
GPT_embedder = Embedder(use_api='openai')

In [4]:
GPT_embedder.get_embedding(['Hello, how are you?', "are you ok?"])

use default model: text-embedding-3-small


array([[ 0.02302372, -0.04998588, -0.01175956, ..., -0.01612528,
        -0.02495578, -0.00749912],
       [-0.00019036, -0.00622486, -0.05782793, ...,  0.02073405,
        -0.01515315, -0.01072091]], dtype=float32)

## JinaAI Embedding (jina-embeddings-v3)
Multilingual embedding model

In [5]:
Jina_embedder = Embedder(use_api='jina')

In [6]:
Jina_embedder.get_embedding(['Hello, how are you?', "are you ok?"])

use default model: jina-embeddings-v3


array([[ 0.03687415, -0.09096006,  0.02410276, ...,  0.01628274,
        -0.02362215, -0.02407126],
       [-0.00227922, -0.1029815 , -0.02208127, ..., -0.00410839,
        -0.0173672 , -0.00483922]], dtype=float32)

## Pytorch embedding (MiniCPM)

In [7]:
CPM_embedder = Embedder(model_name = "openbmb/MiniCPM-Embedding", attn_implementation='flash_attention_2', to_cuda=True)

A new version of the following files was downloaded from https://huggingface.co/openbmb/MiniCPM-Embedding:
- configuration_minicpm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/openbmb/MiniCPM-Embedding:
- modeling_minicpm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|██████████| 2/2 [00:04<00:00,  2.37s/it]


In [8]:
CPM_embedder.get_embedding(['Hello, how are you?', "are you ok?"])

array([[ 0.0250781 , -0.00917552,  0.02117342, ..., -0.02131698,
        -0.03501037,  0.01087992],
       [ 0.02245502, -0.02190519,  0.02482457, ..., -0.00900446,
        -0.03274293,  0.00962162]], dtype=float32)

In [11]:
CPM_embedder_slow = Embedder(model_name = "openbmb/MiniCPM-Embedding", use_api=False, attn_implementation=None, to_cuda=True)

Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.28it/s]


In [12]:
CPM_embedder_slow.get_embedding(['Hello, how are you?', "are you ok?"])

array([[ 0.0250781 , -0.00917552,  0.02117342, ..., -0.02131698,
        -0.03501037,  0.01087992],
       [ 0.02245502, -0.02190519,  0.02482457, ..., -0.00900446,
        -0.03274293,  0.00962162]], dtype=float32)

## Pytorch embedding (llama3-chinese)

In [15]:
llama_embedder = Embedder(model_name="shenzhi-wang/Llama3.1-8B-Chinese-Chat",
                    to_cuda=True)

Loading checkpoint shards: 100%|██████████| 4/4 [00:13<00:00,  3.43s/it]


OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 11.99 GiB of which 0 bytes is free. Of the allocated memory 25.65 GiB is allocated by PyTorch, and 732.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [14]:
llama_embedder.get_embedding(['Hello, how are you?', "are you ok?"])

We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)


array([[-0.02008956, -0.01499601,  0.01133191, ...,  0.01390751,
        -0.01507808,  0.00439701],
       [-0.0220704 ,  0.00496406, -0.00781663, ...,  0.00897674,
        -0.0011227 ,  0.0103637 ]], dtype=float32)